'use client';

import { useEffect, useState } from 'react';
import { useParams, useSearchParams } from 'next/navigation';
import Link from 'next/link';

export default function BrandDashboard() {
  const { id } = useParams();
  const searchParams = useSearchParams();
  const isOnboarding = searchParams.get('onboarding') === 'true';

  const [brand, setBrand] = useState<any>(null);
  const [accounts, setAccounts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchBrandAndAccounts = () => {
    Promise.all([
      fetch(`/api/brand-profiles/${id}`).then(r => r.json()),
      fetch('/api/accounts').then(r => r.json())
    ]).then(([brandData, accountsData]) => {
      setBrand(brandData);
      setAccounts(Array.isArray(accountsData) ? accountsData : []);
      setLoading(false);
    });
  };

  useEffect(() => {
    fetchBrandAndAccounts();

    // Poll if still crawling
    let interval: NodeJS.Timeout;
    if (isOnboarding) {
      interval = setInterval(() => {
        fetch(`/api/brand-profiles/${id}`).then(r => r.json()).then(data => {
          setBrand(data);
        });
      }, 5000);
    }
    return () => clearInterval(interval);
  }, [id, isOnboarding]);

  const updateAccount = async (accountId: string) => {
    try {
      const res = await fetch(`/api/brand-profiles/${id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ connected_account_id: accountId || null })
      });
      if (res.ok) {
        setBrand({ ...brand, connected_account_id: accountId || null });
      }
    } catch (e) {
      console.error(e);
      alert('Failed to link account');
    }
  };

  if (loading) {
    return <div className="text-center py-20 text-gray-500">Loading brand engine...</div>;
  }

  if (!brand || brand.error) {
    return <div className="text-center py-20 text-red-500">Error loading brand.</div>;
  }

  const isReady = brand.onboarding_status === 'ready' || brand.onboarding_status === 'active';

  return (
    <div className="max-w-5xl mx-auto py-10 px-6">
      <div className="flex justify-between items-center border-b border-gray-200 pb-6 mb-8">
        <div>
          <Link href="/brands" className="text-sm text-gray-500 hover:text-blue-600 mb-2 inline-block">← Back to Brands</Link>
          <h1 className="text-3xl font-extrabold">{brand.brand_name} <span className="text-gray-400 font-normal">Dashboard</span></h1>
          <p className="text-gray-500 mt-1">{brand.brand_url}</p>
        </div>
        <div>
          <span className={`px-4 py-2 text-sm font-bold rounded-full ${
            brand.onboarding_status === 'active' ? 'bg-green-100 text-green-700' :
            brand.onboarding_status === 'ready' ? 'bg-blue-100 text-blue-700' :
            brand.onboarding_status === 'crawling' ? 'bg-yellow-100 text-yellow-700 animate-pulse' :
            'bg-gray-100 text-gray-700'
          }`}>
            {brand.onboarding_status === 'crawling' ? 'Analyzing Website...' : 
             brand.onboarding_status === 'ready' ? 'Ready to Activate' : 
             brand.onboarding_status.toUpperCase()}
          </span>
        </div>
      </div>

      {!isReady && (
        <div className="bg-blue-50 border border-blue-200 p-8 rounded-2xl mb-8 text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <h2 className="text-xl font-bold text-blue-900 mb-2">We are crawling {brand.brand_url}</h2>
          <p className="text-blue-700">Extracting value propositions, target audiences, and generating content pillars... this takes a minute or two.</p>
        </div>
      )}

      {isReady && (
        <div className="grid md:grid-cols-3 gap-8">
          <div className="md:col-span-2 space-y-8">
            <section className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
              <h2 className="text-xl font-bold mb-4">Content Pillars (Generated by AI)</h2>
              <div className="space-y-4">
                {brand.pillars?.map((pillar: any) => (
                  <div key={pillar.id} className="p-4 bg-gray-50 rounded-lg border border-gray-100">
                    <div className="flex justify-between items-start mb-2">
                      <h3 className="font-bold text-gray-900">{pillar.name}</h3>
                      <span className="text-xs font-mono bg-gray-200 px-2 py-1 rounded">Weight: {pillar.weight}</span>
                    </div>
                    <p className="text-sm text-gray-600 mb-2">{pillar.description}</p>
                    <div className="text-xs text-gray-500">
                      <strong>Angles:</strong> {pillar.example_angles?.join(', ')}
                    </div>
                  </div>
                ))}
              </div>
            </section>

            <section className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
              <h2 className="text-xl font-bold mb-4">Extracted Knowledge</h2>
              <div className="grid grid-cols-2 gap-4 mb-4">
                <div className="p-4 bg-blue-50 text-blue-900 rounded-lg">
                  <h4 className="font-bold mb-1">Target Audiences</h4>
                  <ul className="list-disc pl-4 text-sm">
                    {brand.target_audiences?.map((a: any, i: number) => <li key={i}>{a.label}</li>)}
                  </ul>
                </div>
                <div className="p-4 bg-purple-50 text-purple-900 rounded-lg">
                  <h4 className="font-bold mb-1">Value Propositions</h4>
                  <ul className="list-disc pl-4 text-sm">
                    {brand.value_propositions?.map((v: any, i: number) => <li key={i}>{v.proposition}</li>)}
                  </ul>
                </div>
              </div>
              <div className="p-4 bg-gray-50 rounded-lg">
                <h4 className="font-bold mb-1">Brand Context</h4>
                <p className="text-sm text-gray-600 whitespace-pre-wrap">{brand.brand_context}</p>
              </div>
            </section>
          </div>

          <div className="space-y-8">
            <section className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
              <h2 className="text-xl font-bold mb-4">Settings</h2>
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Brand Voice</label>
                  <textarea 
                    className="w-full text-sm p-2 border border-gray-300 rounded focus:outline-none" 
                    rows={3} 
                    defaultValue={brand.brand_voice} 
                    readOnly
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Never Say (Constraints)</label>
                  <div className="flex flex-wrap gap-2">
                    {brand.never_say?.map((w: string, i: number) => (
                      <span key={i} className="bg-red-100 text-red-800 text-xs px-2 py-1 rounded">{w}</span>
                    ))}
                  </div>
                </div>
              </div>
            </section>

            <section className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
              <h2 className="text-xl font-bold mb-4">Activation</h2>
              <p className="text-sm text-gray-600 mb-4">
                To start the automated engine, you must connect a Twitter or LinkedIn account and assign it to this brand.
              </p>
              
              <div className="mb-4">
                <label className="block text-sm font-medium text-gray-700 mb-1">Assigned Account</label>
                <select 
                  className="w-full text-sm p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                  value={brand.connected_account_id || ''}
                  onChange={(e) => updateAccount(e.target.value)}
                >
                  <option value="">-- No Account Selected --</option>
                  {accounts.map(acc => (
                    <option key={acc.id} value={acc.id}>
                      {acc.platform.toUpperCase()} - @{acc.account_username}
                    </option>
                  ))}
                </select>
              </div>

              {!brand.connected_account_id && (
                <Link href="/setup/integrations" className="block w-full text-center bg-blue-600 text-white font-bold py-3 rounded-lg hover:bg-blue-700">
                  Connect New Account
                </Link>
              )}
            </section>
          </div>
        </div>
      )}
    </div>
  );
}
