// lib/threadGenerationService.ts
import OpenAI from 'openai';
import { getPersonaByKey, PersonaConfig } from '@/lib/personas';
import { createThread, saveTweet, generateTweetId } from './db';
import { accountService } from './accountService';
import type { Account, Tweet } from './types';
import { logger } from '@/lib/logger'; 

const deepseekClient = new OpenAI({
  apiKey: process.env.DEEPSEEK_API_KEY,
  baseURL: 'https://api.deepseek.com',
});

// MODIFIED: Added rssContext to the config
export interface ThreadGenerationConfig {
  account_id: string;
  persona: string;
  rssContext?: string; // The news briefing
}

// MODIFIED: Added sourceUrl to the result
export interface ThreadGenerationResult {
  thread_id: string;
  total_tweets: number;
  tweets: Tweet[];
  story_category: string;
  sourceUrl?: string;
}

/**
 * Split a long tweet into multiple tweets at natural break points
 */
function splitLongTweet(content: string): string[] {
  const maxLength = 280;
  
  if (content.length <= maxLength) {
    return [content];
  }
  
  const tweets: string[] = [];
  let remaining = content.trim();
  
  while (remaining.length > maxLength) {
    // Find natural break points in order of preference
    let splitIndex = maxLength;
    
    // Try to split at sentence endings (. ! ?)
    let lastSentence = remaining.lastIndexOf('.', maxLength);
    if (lastSentence === -1) lastSentence = remaining.lastIndexOf('!', maxLength);
    if (lastSentence === -1) lastSentence = remaining.lastIndexOf('?', maxLength);
    
    if (lastSentence > maxLength * 0.6) { // Don't split too early
      splitIndex = lastSentence + 1;
    } else {
      // Try to split at comma or semicolon
      let lastPunctuation = remaining.lastIndexOf(',', maxLength);
      if (lastPunctuation === -1) lastPunctuation = remaining.lastIndexOf(';', maxLength);
      
      if (lastPunctuation > maxLength * 0.7) {
        splitIndex = lastPunctuation + 1;
      } else {
        // Split at last space to avoid breaking words
        const lastSpace = remaining.lastIndexOf(' ', maxLength);
        if (lastSpace > maxLength * 0.5) {
          splitIndex = lastSpace;
        }
      }
    }
    
    // Extract the tweet and clean up
    const tweetContent = remaining.substring(0, splitIndex).trim();
    tweets.push(tweetContent);
    
    // Continue with remaining content  
    remaining = remaining.substring(splitIndex).trim();
  }
  
  // Add the final piece
  if (remaining.length > 0) {
    tweets.push(remaining);
  }
  
  logger.info(`✂️ Split long tweet into ${tweets.length} parts:`, 'thread-split', tweets.map(t => `${t.length} chars`));
  return tweets;
}


/**
 * Generate thread-specific prompt for storytelling (business or cricket)
 */
// MODIFIED: Function signature updated to accept rssContext
function generateThreadPrompt(persona?: PersonaConfig, rssContext?: string): string {
  const timeMarker = `T${Date.now()}`;
  const tokenMarker = `TK${Math.random().toString(36).substring(2, 8).toUpperCase()}`;
  const diversityMarker = `D${Math.random().toString(36).substring(2, 4).toUpperCase()}`;
  
  // Get persona-specific context from persona config instead of hardcoding
  const storyContext = persona?.description || 'Expert storyteller creating compelling narratives';
  


  // MODIFIED: Add the news briefing to the prompt if it exists
  const deepDiveBriefing = rssContext
    ? `\n\nINTELLIGENCE BRIEFING (Primary Source of Truth):
-------------------------------------------------
${rssContext}
-------------------------------------------------\n`
    : '';

  // Hashtags are now generated by AI contextually - no predefined hashtags needed
  const personaHashtags: string[] = [];
  
  const isBusinessPersona = persona?.key === 'business_storyteller';
  const isCricketPersona = persona?.key === 'cricket_storyteller';
  
  // Context-specific requirements based on persona
  const specificRequirements = isBusinessPersona 
    ? `• Focus on authentic business stories with strategic insights
• Include specific details, numbers, and concrete outcomes  
• Connect with Indian business culture and context
• Blend business strategy with human elements`
    : isCricketPersona 
    ? `• Focus on authentic cricket stories with psychological depth
• Include match details, scores, and specific moments
• Connect cricket situations to universal human themes
• Highlight character revelations and life lessons`
    : `• Focus on authentic, engaging stories with emotional depth
• Include specific details and memorable moments
• Connect with universal human themes`;

  return `${storyContext}

${deepDiveBriefing}
CREATIVE APPROACH:
• If an Intelligence Briefing is provided, your story MUST be based on the "Primary News Item" within it. Use the other details for context.
• Find compelling, lesser-known stories or fresh angles on known stories
• Use conversational storytelling tone with natural flow
• Include human elements and specific, memorable details
• Each thread should be completely unique and original

PERSONA-SPECIFIC REQUIREMENTS:
${specificRequirements}
• Use real X (formerly Twitter) handles (@username) when mentioning people/companies
• Each tweet should be standalone engaging while advancing the story


TWEET SHAREABILITY - CRITICAL FOR VIRALITY:
• EVERY SINGLE TWEET must be a COMPLETE, shareable statement that delivers standalone value
• Each tweet should be quotable and screenshot-worthy - people should want to share individual tweets even without the full thread
• Use power words, specific numbers, dramatic contrasts, and concrete details in EVERY tweet
• Include emotional elements (inspiration, shock, wisdom, surprise) throughout the thread

FIRST TWEET REQUIREMENTS (THE HOOK):
• The opening tweet is THE MOST IMPORTANT - it sets the tone and drives clicks
• Must deliver a complete insight, fact, or story summary upfront
• Examples of complete, shareable first tweets:
  - "In 2008, Narayana Murthy took a 100% pay cut to save Infosys from bankruptcy. That decision saved 10,000 jobs and built a $2B company."
  - "The 7-minute meeting between Dhoni and Kohli in 2014 changed Indian cricket's leadership philosophy forever. Here's what happened in that room."
  - "Ritesh Agarwal dropped out of college at 17, got rejected by 100 investors, and turned a $25,000 loan into OYO - India's youngest unicorn. The full story:"
• First tweet delivers the GIST - who, what, outcome. Thread adds the "how" and "why".

MIDDLE & ENDING TWEETS REQUIREMENTS:
• Each subsequent tweet must advance the story while being independently valuable
• Make every tweet quotable with specific insights, numbers, or revelations
• Use cliffhangers, surprises, and "turning points" to maintain engagement
• Final tweet should include a powerful lesson or takeaway that stands alone
• Avoid filler tweets - every single tweet must earn its place in the thread


CHARACTER LIMITS - ABSOLUTELY CRITICAL:
• EACH TWEET MUST BE UNDER 240 CHARACTERS (including thread indicators like "1/7")
• Thread indicators (1/7, 2/7, etc.) count toward the 240 character limit
• Aim for 160-220 characters per tweet for better readability
• If any tweet exceeds 240 characters, IMMEDIATELY break it into multiple shorter tweets
• Better to have more tweets than overly long ones that get truncated

Generate a complete thread. Return ONLY valid JSON:

{
  "title": "Thread title",
  "story_category": "Story Category",
  "hashtags": ${JSON.stringify(personaHashtags)},
  "tweets": [
    {"sequence": 1, "content": "Tweet 1 content"},
    {"sequence": 2, "content": "Tweet 2 content"}
  ]
}

[${timeMarker}-${tokenMarker}-${diversityMarker}]`;
}


/**
 * Parse and validate thread generation response
 */
// MODIFIED: Function signature updated to parse rssContext and return a sourceUrl
function parseThreadResponse(
  content: string,
  rssContext?: string
): {
  title: string;
  story_category: string;
  hashtags: string[];
  tweets: Array<{ sequence: number; content: string }>;
  sourceUrl: string | undefined;
} | null {
  try {
    const cleanedContent = content.replace(/```json\n?|\n?```/g, '').trim();
    const data = JSON.parse(cleanedContent);
    
    if (!data.title || !data.tweets || !Array.isArray(data.tweets) || !data.hashtags || !Array.isArray(data.hashtags)) {
      throw new Error('AI response missing required fields');
    }
    
    if (data.tweets.length < 3 || data.tweets.length > 10) {
      throw new Error(`Thread length should be reasonable (3-10 tweets), got ${data.tweets.length}`);
    }

    // MODIFIED: Extract sourceUrl from the context string
    let sourceUrl: string | undefined;
    if (rssContext) {
      const sourcePattern = /Source URL \(for context\): (https?:\/\/\S+)/m;
      const match = rssContext.match(sourcePattern);
      if (match && match[1]) {
        sourceUrl = match[1].trim();
        logger.info(`📰 [Thread] Extracted Primary News Item source: ${sourceUrl}`, 'thread-source-extraction');
      }
    }
    
    // Validate tweet structure and handle character limits
    const processedTweets = [];
    for (let i = 0; i < data.tweets.length; i++) {
      const tweet = data.tweets[i];
      if (!tweet.content || typeof tweet.content !== 'string') {
        throw new Error(`Tweet ${i + 1} missing content`);
      }
      
      // Character validation and overflow handling
      if (tweet.content.length > 280) {
        logger.warn(`Tweet ${i + 1} is too long (${tweet.content.length} chars), splitting into multiple tweets...`, 'thread-validation');
        
        // Split at natural break points (sentences, clauses)
        const splitTweets = splitLongTweet(tweet.content);
        
        // Add split tweets with correct sequencing
        splitTweets.forEach((content) => {
          processedTweets.push({
            sequence: processedTweets.length + 1,
            content: content
          });
        });
      } else {
        processedTweets.push({
          sequence: processedTweets.length + 1,
          content: tweet.content
        });
      }
    }
    
    // Validate final length
    if (processedTweets.length > 15) {
      throw new Error(`Thread too long after splitting: ${processedTweets.length} tweets (max 15)`);
    }
    
    return {
      title: data.title,
      story_category: data.story_category,
      hashtags: data.hashtags,
      tweets: processedTweets,
      sourceUrl, //MODIFIED: Include extracted URL in the return object
    };
  } catch (error) {
    logger.error(`Failed to parse thread response: ${error}`, 'thread-parsing-error');
    return null;
  }
}


/**
 * Main thread generation function
 */
export async function generateThread(config: ThreadGenerationConfig): Promise<ThreadGenerationResult | null> {
  const startTime = performance.now();
  const callId = Math.random().toString(36).substring(2, 8); 

  try {
    logger.info(`[Thread:${callId}] Starting thread generation for account: ${config.account_id}, persona: ${config.persona}`, 'thread-start');
    
    // --- Initial DB Read ---
    const dbReadStart = performance.now();
    const account = await accountService.getAccount(config.account_id);
    if (!account) {
      throw new Error(`Account not found: ${config.account_id}`);
    }
    
    const persona = getPersonaByKey(config.persona);
    if (!persona) {
      throw new Error(`Persona not found: ${config.persona}`);
    }
    
    if (!persona.content_types?.includes('thread')) {
      throw new Error(`Persona ${config.persona} does not support threading`);
    }
    const dbReadDuration = ((performance.now() - dbReadStart) / 1000).toFixed(2);
    logger.info(`[Thread:${callId}] Initial DB read time: ${dbReadDuration}s`, 'thread-timing');
    
    
    // MODIFIED: Pass rssContext to the prompt generator
    const prompt = generateThreadPrompt(persona, config.rssContext);
    
    logger.info(`[Thread:${callId}] Sending thread generation request to DeepSeek (prompt length: ${prompt.length} chars)`, 'thread-llm-call');
    
    // --- LLM API Call (max_tokens reduced from 3000 to 1500 for potential latency gain) ---
    const llmCallStart = performance.now();
    const response = await deepseekClient.chat.completions.create({
      model: "deepseek-chat",
      messages: [{ role: "user", content: prompt }],
      temperature: 0.8, 
      max_tokens: 1500, // OPTIMIZATION: Reduced max_tokens 
      stream: false, 
    });

    const llmCallDuration = ((performance.now() - llmCallStart) / 1000).toFixed(2);
    logger.info(`[Thread:${callId}] DeepSeek LLM call duration: ${llmCallDuration}s`, 'thread-timing');

    const aiContent = response.choices[0].message.content;
    if (!aiContent) {
      throw new Error('AI returned no content for thread generation');
    }

    // MODIFIED: Pass rssContext to the response parser
    const threadData = parseThreadResponse(aiContent, config.rssContext);
    if (!threadData) {
      throw new Error('Failed to parse or validate thread response');
    }

    logger.info(`[Thread:${callId}] Generated thread: "${threadData.title}" with ${threadData.tweets.length} tweets`, 'thread-generation-success');

    // --- DB Write Operations ---
    const dbWriteStart = performance.now();

    // Create thread record in database
    const threadId = await createThread({
      account_id: config.account_id,
      title: threadData.title,
      persona: config.persona,
      total_tweets: threadData.tweets.length,
      status: 'ready',
      story_category: threadData.story_category
    });

    // Use AI-generated hashtags from the thread response with validation
    const hashtags = threadData.hashtags.map(tag => {
      // Remove any existing # symbols and ensure single # prefix
      const cleanTag = tag.replace(/^#+/, '').trim();
      return cleanTag ? `#${cleanTag}` : '';
    }).filter(tag => tag.length > 1); // Remove empty tags

    // Create and save individual tweets 
    const tweets: Tweet[] = [];
    const tweetsToSave: Tweet[] = [];
    
    for (const tweetData of threadData.tweets) {
      const tweetId = generateTweetId();
      
      const threadedContent = tweetData.content;
      
      const tweet: Tweet = {
        id: tweetId,
        account_id: config.account_id,
        content: threadedContent,
        hashtags: hashtags,
        persona: config.persona,
        status: 'ready',
        created_at: new Date().toISOString(),
        // Threading fields
        thread_id: threadId,
        thread_sequence: tweetData.sequence,
        content_type: 'thread',
        // MODIFIED: Add source_url ONLY to the first tweet of the thread
        source_url: tweetData.sequence === 1 ? threadData.sourceUrl : undefined,
      };

      tweetsToSave.push(tweet);
      tweets.push(tweet);
    }
    
    // OPTIMIZATION: Convert sequential saves to concurrent Promise.all
    // This targets the 5.94s DB write time for 7 tweets.
    await Promise.all(tweetsToSave.map(tweet => saveTweet(tweet)));


    const dbWriteDuration = ((performance.now() - dbWriteStart) / 1000).toFixed(2);
    logger.info(`[Thread:${callId}] DB write time (create thread + save ${tweetsToSave.length} tweets): ${dbWriteDuration}s`, 'thread-timing');
    
    const totalDuration = ((performance.now() - startTime) / 1000).toFixed(2);
    logger.info(`[Thread:${callId}] Thread generation complete. Total duration: ${totalDuration}s`, 'thread-complete', {
      total_duration_s: parseFloat(totalDuration),
      llm_duration_s: parseFloat(llmCallDuration),
      total_tweets: tweets.length
    });

    // MODIFIED: Include sourceUrl in the final return object
    return {
      thread_id: threadId,
      total_tweets: tweets.length,
      tweets: tweets,
      story_category: threadData.story_category,
      sourceUrl: threadData.sourceUrl,
    };

  } catch (error) {
    const totalDuration = ((performance.now() - startTime) / 1000).toFixed(2);
    logger.error(`[Thread:${callId}] ❌ Thread generation failed after ${totalDuration}s:`, 'thread-failure', error as Error);
    return null;
  }
}


/**
 * Get thread generation eligibility for account
 */
export function canGenerateThreads(account: Account): boolean {
  // Currently only Prince's business account supports threading
  const handle = account.twitter_handle.toLowerCase();
  
  // Specific accounts that should NOT generate threads (Gibbi's educational accounts)
  const excludedHandles = ['@gibbi_ai', 'gibbi_ai'];
  if (excludedHandles.includes(handle) || excludedHandles.includes(handle.replace('@', ''))) {
    return false;
  }
  
  // Specific accounts that CAN generate threads (Prince's business accounts)
  const allowedHandles = ['@princediwakar25', 'princediwakar25'];
  return allowedHandles.includes(handle) || allowedHandles.includes(handle.replace('@', ''));
}

const threadGenerationService = {
  generateThread,
  canGenerateThreads
};

export default threadGenerationService;